name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build
        run: |
          NODE_ENV=development npm install && npm run build --if-present
          if [[ $(find . -maxdepth 1 -type d -name 'dist') == '' ]]
          then
            cp -r public dist
          fi
          mkdir actions_artifacts
          mv dist actions_artifacts

      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: actions_artifacts
          path: actions_artifacts
