name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build
        run: |
          npm install
          npm run build --if-present || echo "No build script found"
          if [[ ! -d "dist" ]]; then
            cp -r public dist
          fi
          mkdir actions_artifacts
          mv dist actions_artifacts

      - name: Save build
        uses: actions/upload-artifact@v3
        with:
          name: actions_artifacts
          path: actions_artifacts
