name: Publish

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download build
        uses: dawidd6/action-download-artifact@v3
        with:
          name: actions_artifacts
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Deploy build to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          git-config-name: "keksobot"
          git-config-email: "github+keksobot@htmlacademy.ru"
          target-folder: ${{ env.PR }}
          commit-message: "✔️ Сборка #${{ env.PR }}"

      - name: Output published URL
        run: |
            echo "Ваш пулреквест опубликован. Посмотреть можно [здесь](https://${{ env.BUILD_URL }}/${{ env.PR }}/)
          pr_number: ${{ env.PR }}"
